name: Build Windows MSI Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Use System Kotlin
        run: kotlinc -version

      - name: Grant execute permission for Gradlew
        run: |
          icacls gradlew /grant Everyone:F
      - name: Build Windows MSI
        run: ./gradlew packageMSI
      - name: List root directory contents for debugging
        run: |
          Get-ChildItem -Recurse
      - name: List directory contents for debugging
        run: dir build\compose\binaries\main
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./build/compose/binaries/main/*.msi  

