name: Build Windows MSI Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0

      - name: Grant execute permission for Gradlew
        run: |
          icacls gradlew /grant Everyone:F

      - name: Build Windows MSI
        run: .\gradlew.bat buildWindowsMsi
